
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >-
          Thanks for submitting an issue! I'll check it at as soon as possible
          and get back to you.
        pr-message: >-
          Thanks for submitting a PR. If the PR is a valid and passes
          all the checks , we will approve it soon. Have a great day!

  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
    - name: Issue notification
      uses: niniyas/ntfy-action@master
      if: github.event_name == 'issues'
      with:
        url: 'https://notifications.compuguy.dev'
        topic: 'github'
        tags: issue
        details: An issue has been submitted by ${{ github.actor }}. Please act soon.
    - name: Pull request notification
      uses: niniyas/ntfy-action@master
      if: github.event_name == 'pull_request'
      with:
        url: 'https://notifications.compuguy.dev'
        topic: 'github'
        tags: issue
        details: A pull request has been submitted by ${{ github.actor }}. Please act soon.
